AllCops:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'
    - 'config/**/*'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 30
